FROM python:latest

WORKDIR /app

ENV VIRTUAL_ENV /app/venv
RUN python -m venv $VIRTUAL_ENV

ENV PATH $VIRTUAL_ENV/bin:$PATH

COPY ./requirements.txt ./
RUN pip install -r requirements.txt --no-cache-dir

COPY ./ ./